aws_region                      = "eu-west-2"
environment                     = "dev"
business_division               = "devops"
codepipeline_bucket_name_prefix = "rk-codepipeline-iac"
codepipeline_github_repository  = "rtdevx/terraform-iac-aws-cp1"